#! /bin/sh
# application.secret
PLAY2STORE_APPLICATION_SECRET="c1P^j5e_ltEkL:]U@?uH=A^E>A1DK^lA2vaGs2a7xsBC_XpOU8M>nj_A=MrJDH;Q"; export PLAY2STORE_APPLICATION_SECRET

# store.stripe.publishable_key
PLAY2STORE_STRIPE_PUBLISHABLE_KEY="pk_DMsUvbcftSZAXsPP5Hl1SIljA9Nrn"; export PLAY2STORE_STRIPE_PUBLISHABLE_KEY

# store.stripe.secret_key
PLAY2STORE_STRIPE_SECRET_KEY="wTyk1HhIXmISfDV65ETQnJQSOYj69S7K"; export PLAY2STORE_STRIPE_SECRET_KEY